- hosts: localhost

  pre_tasks:
    - name: update repositories on Ubuntu
      when: ansible_distribution == 'Ubuntu'
      become: yes
      apt: 
        update_cache: yes
        upgrade: yes
      changed_when: False

  tasks:
    - include_tasks: tasks/01-packages-apt.yml
      when: ansible_distribution == 'Ubuntu'
    - include_tasks: tasks/02-asdf.yml
    - include_tasks: tasks/03-environment.yml
