- name: Clone asdf repository
  become: yes
  become_user: "{{ user }}"
  git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: "/home/{{ user }}/.asdf"
    version: "v0.14.0"

- name: Add asdf plugins
  command: "/home/{{ user }}/.asdf/bin/asdf plugin-add {{ item }}"
  become: yes
  become_user: "{{ user }}"
  with_items:
    - neovim
    - golang
    - kubectl
    - helm
    - terraform

- name: Install asdf plugin
  command: "~{{ user }}/.asdf/bin/asdf install {{ item }}"
  become: yes
  become_user: "{{ user }}"
  with_items:
    - neovim 0.10.0
    - kubectl 1.28.10 
    - golang 1.22.4

- name: Set global versions
  command: "~{{ user }}/.asdf/bin/asdf global {{ item }}"
  become: yes
  become_user: "{{ user }}"
  with_items:
    - neovim 0.10.0
    - kubectl 1.28.10 
    - golang 1.22.4
