- name: Copy bash files
  copy:
    src: "environment/bash/{{ item }}"
    dest: "~{{ user }}/{{ item }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0644"
  with_items:
    - .bashrc
    - .inputrc
    - .bash_logout
    - .bash_profile

- name: Copy bash helper directory
  copy:
    src: "environment/bash/.bash"
    dest: "~{{ user }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0755"
